/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoborrador;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;

/**
 *
 * @author XPC
 */
public class BorradorGUI extends javax.swing.JFrame {
    public ArrayList<Zombie> Zombies;
    public ArrayList<Arma> Armas;
    private Partida partidaActual;
    private JLabel[][] matrizDeEtiquetas = new JLabel[25][25];


    /**
     * Creates new form BorradorGUI
     */
    public BorradorGUI() {
        Zombies = new ArrayList<Zombie>();
        Armas = new ArrayList<Arma>();
        initComponents();
        
        Partida prueba = new Partida(jPanelMatriz);
        partidaActual = prueba;
        
        setResizable(false);
        setPreferredSize(new Dimension(1200, 600));
        
        jPanelBienvenida.setLayout(null);
        this.add(jPanelBienvenida);
        jPanelBienvenida.setBounds(0, 0, 1200, 600);
        jPanelBienvenida.add(jButtonFile);
        
        ImageIcon icon = new ImageIcon(new ImageIcon("./src/Images/welcome.jpg").getImage().getScaledInstance(1200, 600, Image.SCALE_SMOOTH));
        
        jLabelBackground.setIcon(icon);
        jPanelBienvenida.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 1200, 600);
        jLabelBackground.setText("");
        
        
        jButtonFile.setBounds(1000, 400, 150, 100);
        jButtonFile.setText("Cargar Partida");
        
        
        
        jButtonFile.setVisible(true);
        jLabelBackground.setVisible(true);
        jPanelBienvenida.setVisible(true);

        pack();
        jPanelNivel.setLayout(null);
        this.add(jPanelNivel);
        jPanelNivel.setBounds(0, 0, 1200, 30);

        jPanelNivel.add(jLabelNivel);
        jLabelNivel.setText("Nivel: " + partidaActual.getNivel());
        jLabelNivel.setVisible(false);
        jLabelNivel.setBounds(5, 5, 50, 20);

        jPanelNivel.add(jButtonJugar);
        jButtonJugar.setBounds(1100, 5, 70, 20);

        jPanelNivel.setVisible(false);

        this.add(jPanelMatriz);
        jPanelMatriz.setLayout(null);
        jPanelMatriz.setBounds(0, 30, 1200, 570);
        jPanelMatriz.setVisible(false);
        
        

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNivel = new javax.swing.JPanel();
        jLabelNivel = new javax.swing.JLabel();
        jButtonJugar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelMatriz = new javax.swing.JPanel();
        jPanelBienvenida = new javax.swing.JPanel();
        jLabelBackground = new javax.swing.JLabel();
        jButtonFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelNivel.setLayout(null);

        jLabelNivel.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanelNivel.add(jLabelNivel);
        jLabelNivel.setBounds(0, 0, 40, 20);

        jButtonJugar.setText("Iniciar");
        jButtonJugar.setAlignmentX(1050.0F);
        jButtonJugar.setMaximumSize(new java.awt.Dimension(50, 20));
        jButtonJugar.setMinimumSize(new java.awt.Dimension(50, 20));
        jButtonJugar.setPreferredSize(new java.awt.Dimension(50, 20));
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        jPanelNivel.add(jButtonJugar);
        jButtonJugar.setBounds(320, 0, 70, 20);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelNivel.add(jButton1);
        jButton1.setBounds(240, 0, 75, 23);

        getContentPane().add(jPanelNivel);
        jPanelNivel.setBounds(0, 0, 400, 30);

        jPanelMatriz.setLayout(null);
        getContentPane().add(jPanelMatriz);
        jPanelMatriz.setBounds(0, 30, 0, 0);

        jPanelBienvenida.setLayout(null);
        jPanelBienvenida.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 400, 300);

        jButtonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileActionPerformed(evt);
            }
        });
        jPanelBienvenida.add(jButtonFile);
        jButtonFile.setBounds(310, 210, 80, 70);

        getContentPane().add(jPanelBienvenida);
        jPanelBienvenida.setBounds(0, 0, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(new ImageIcon("./src/Images/reliquia.png").getImage().getScaledInstance(45, 30, Image.SCALE_SMOOTH));

        matrizDeEtiquetas[12][12].setIcon(icon);
              
        
        Juego game = new Juego(jPanelMatriz, matrizDeEtiquetas, partidaActual);
        game.start();
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jButtonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        this.partidaActual = (Partida) FileManager.readObject(chooser.getSelectedFile().getAbsolutePath());

        jButtonFile.setVisible(false);
        jLabelBackground.setVisible(false);
        jPanelBienvenida.setVisible(false);

        Border border = BorderFactory.createLineBorder(java.awt.Color.BLACK);

        int x = 100;
        int y = 10;
        for (int i = 0; i < 25; i++) {
            for (int j = 0; j < 25; j++) {
                matrizDeEtiquetas[i][j] = new JLabel();
                for (int k = 0; k < partidaActual.getArmas().size(); k++) {
                    if(partidaActual.getArmas().get(k).getFila() == i && partidaActual.getArmas().get(k).getColumna() == j){
                        matrizDeEtiquetas[i][j] = partidaActual.getArmas().get(k).getLabel();
                        ImageIcon icon = new ImageIcon(new ImageIcon(partidaActual.getArmas().get(k).getGif()).getImage().getScaledInstance(45, 30, Image.SCALE_SMOOTH));
                        matrizDeEtiquetas[i][j].setIcon(icon);
                    }                    
                }
                matrizDeEtiquetas[i][j].setText("");
                jPanelMatriz.add(matrizDeEtiquetas[i][j]);
                matrizDeEtiquetas[i][j].setBounds(x, y, 40, 20);
                matrizDeEtiquetas[i][j].setBorder(border);
                //jPanelMatriz.repaint();
                x += 40;
            }
            x = 100;
            y += 20;
        }

        jLabelNivel.setVisible(true);
        jButtonJugar.setBounds(1100, 5, 70, 20);
        jPanelNivel.setVisible(true);
        jPanelMatriz.setVisible(true);

        pack();
    }//GEN-LAST:event_jButtonFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorradorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonFile;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JPanel jPanelBienvenida;
    private javax.swing.JPanel jPanelMatriz;
    private javax.swing.JPanel jPanelNivel;
    // End of variables declaration//GEN-END:variables
}
