/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoborrador;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;

/**
 *
 * @author XPC
 */
public class BorradorGUI extends javax.swing.JFrame {
    public ArrayList<Zombie> Zombies;
    public ArrayList<Arma> Armas;
    private Partida partidaActual;
    private JLabel[][] matrizDeEtiquetas = new JLabel[25][25];


    /**
     * Creates new form BorradorGUI
     */
    public BorradorGUI() {
        Zombies = new ArrayList<Zombie>();
        Armas = new ArrayList<Arma>();
        initComponents();
        
        Partida prueba = new Partida(jPanelMatriz);
        partidaActual = prueba;
        
        setResizable(false);
        setPreferredSize(new Dimension(1200, 600));
        
        jPanelNivel.setLayout(null);
        this.add(jPanelNivel);
        jPanelNivel.setBounds(0, 0, 1200, 30);

        jPanelNivel.add(jLabelNivel);
        jLabelNivel.setText("Nivel: " + partidaActual.getNivel());
        jLabelNivel.setVisible(true);
        jLabelNivel.setBounds(5, 5, 50, 20);

        jPanelNivel.add(jButtonJugar);
        jButtonJugar.setBounds(1100, 5, 70, 20);


        jPanelNivel.setVisible(true);
        
        this.add(jPanelMatriz);
        jPanelMatriz.setLayout(null);
        jPanelMatriz.setBounds(0, 30, 1200, 570);
        jPanelMatriz.setVisible(true);

        Border border = BorderFactory.createLineBorder(java.awt.Color.BLACK);
        
        int x = 100;
        int y = 10;
        for (int i = 0; i < 25; i++) {
            for (int j = 0; j < 25; j++) {
                matrizDeEtiquetas[i][j] = new JLabel();
                matrizDeEtiquetas[i][j].setText("");
                jPanelMatriz.add(matrizDeEtiquetas[i][j]);
                matrizDeEtiquetas[i][j].setBounds(x, y, 40, 20);
                matrizDeEtiquetas[i][j].setBorder(border);
                //jPanelMatriz.repaint();
                x += 40;
            }
            x = 100;
            y += 20;
        }
        pack();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNivel = new javax.swing.JPanel();
        jLabelNivel = new javax.swing.JLabel();
        jButtonJugar = new javax.swing.JButton();
        jPanelMatriz = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelNivel.setLayout(null);

        jLabelNivel.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanelNivel.add(jLabelNivel);
        jLabelNivel.setBounds(0, 0, 40, 20);

        jButtonJugar.setText("Iniciar");
        jButtonJugar.setAlignmentX(1050.0F);
        jButtonJugar.setMaximumSize(new java.awt.Dimension(50, 20));
        jButtonJugar.setMinimumSize(new java.awt.Dimension(50, 20));
        jButtonJugar.setPreferredSize(new java.awt.Dimension(50, 20));
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        jPanelNivel.add(jButtonJugar);
        jButtonJugar.setBounds(320, 0, 70, 20);

        getContentPane().add(jPanelNivel);
        jPanelNivel.setBounds(0, 0, 400, 30);

        jPanelMatriz.setLayout(null);
        getContentPane().add(jPanelMatriz);
        jPanelMatriz.setBounds(0, 30, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(new ImageIcon("./src/Images/reliquia.png").getImage().getScaledInstance(45, 30, Image.SCALE_SMOOTH));

        matrizDeEtiquetas[12][12].setIcon(icon);
        
        Partida pprueba = new Partida(jPanelMatriz);

        Zombie z1 = new Zombie("Juan", "Aereo", 50, 10, 1, "./src/Images/zContacto1.png", "./src/Images/zContacto2.png", 2);
        Arma a1 = new Arma("Guillermo Edgardo", "Aereo", 50, 5, 1, "./src/Images/zContacto1.png", "./src/Images/zContacto1.png", 2);
        a1.setFila(16);
        a1.setColumna(16);
        a1.setGUI(jPanelMatriz);
        a1.setPosX(matrizDeEtiquetas[16][16].getX());
        a1.setPosY(matrizDeEtiquetas[16][16].getY());
        z1.setGUI(jPanelMatriz);


        pprueba.addArma(a1);
        pprueba.addZombie(z1);

        for (int c = 0; c < pprueba.getArmas().size(); c++) {
            Border border = BorderFactory.createLineBorder(java.awt.Color.BLACK);
            icon = new ImageIcon(new ImageIcon(pprueba.getArmas().get(c).getGif()).getImage().getScaledInstance(45, 30, Image.SCALE_SMOOTH));
            jPanelMatriz.add(pprueba.getArmas().get(c).getLabel());
            pprueba.getArmas().get(c).getLabel().setBounds(pprueba.getArmas().get(c).getPosX(), pprueba.getArmas().get(c).getPosX(), 40, 20);
            pprueba.getArmas().get(c).getLabel().setBorder(border);
            pprueba.getArmas().get(c).getLabel().setIcon(icon);
            matrizDeEtiquetas[pprueba.getArmas().get(c).getFila()][pprueba.getArmas().get(c).getColumna()].setIcon(icon);
            //matrizDeEtiquetas[pprueba.getArmas().get(c).getFila()][pprueba.getArmas().get(c).getColumna()].setIcon(icon);
            //matrizDeEtiquetas[pprueba.getArmas().get(c).getFila()][pprueba.getArmas().get(c).getColumna()] = pprueba.getArmas().get(c).getLabel();
            pprueba.getArmas().get(c).setLabel(matrizDeEtiquetas[pprueba.getArmas().get(c).getFila()][pprueba.getArmas().get(c).getColumna()]);
            pprueba.getArmas().get(c).getLabel().setVisible(true);
        }
        
        Juego game = new Juego(jPanelMatriz, matrizDeEtiquetas, pprueba);
        game.start();
    }//GEN-LAST:event_jButtonJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorradorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JPanel jPanelMatriz;
    private javax.swing.JPanel jPanelNivel;
    // End of variables declaration//GEN-END:variables
}
